import { useState } from "react";

const Icon = ({ name, size = 20 }) => {
  const paths = { grid: "M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z", user: "M20 21a8 8 0 0 0-16 0M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z", leaf: "M20 4C12 4 5 7 5 14c0 3 2 6 5 6 7 0 10-7 10-16ZM5 20c3-5 7-8 12-10", check: "m5 12 4 4L19 6", chart: "M4 20V10M10 20V4M16 20v-7M22 20H2", wallet: "M4 7a3 3 0 0 1 3-3h12a2 2 0 0 1 2 2v13a1 1 0 0 1-1 1H6a3 3 0 0 1-3-3V7Zm0 3h17M17 15h.01", users: "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75", bell: "M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4", chevron: "m9 18 6-6-6-6", map: "M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0ZM12 10a2 2 0 1 0 0 .01", shield: "M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Zm-3-10 2 2 4-4", file: "M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Zm0 0v6h6M8 13h8M8 17h6", arrow: "M5 12h14m-6-6 6 6-6 6", dots: "M5 12h.01M12 12h.01M19 12h.01", menu: "M4 6h16M4 12h16M4 18h16" };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name]} /></svg>;
};
const nav = [["grid", "Overview"], ["user", "My profile"], ["leaf", "Farm records"], ["check", "Verifications"], ["chart", "Credit profile"], ["wallet", "Loans & offers"], ["users", "My community"]];
const steps = [["user", "Profile", "Complete"], ["file", "Farm data", "Verified"], ["shield", "Community", "Validated"], ["chart", "Credit profile", "Ready"]];

export default function App() {
  const [active, setActive] = useState("Overview");
  return <div className="shell"><aside className="sidebar"><div className="logo"><span className="logo-mark"><Icon name="leaf" size={22}/></span><span>Kissan<span>Trust</span></span></div><div className="workspace-label">FARMER WORKSPACE</div><nav>{nav.map(([icon, label]) => <button key={label} onClick={() => setActive(label)} className={`nav-item ${active === label ? "active" : ""}`}><Icon name={icon}/><span>{label}</span>{label === "Loans & offers" && <b>2</b>}</button>)}</nav><div className="side-support"><div className="support-icon"><Icon name="users"/></div><div><strong>Need help?</strong><span>Talk to your FPO advisor</span></div><Icon name="chevron" size={16}/></div><div className="sidebar-bottom"><span>© 2026 KissanTrust</span><span>Privacy & data rights</span></div></aside>
  <main className="main"><header className="topbar"><div className="mobile-menu"><Icon name="menu"/></div><div className="crumb">Workspace <span>/</span> <b>{active}</b></div><div className="top-actions"><button className="icon-button"><Icon name="bell"/><i></i></button><div className="user-chip"><img src="https://images.unsplash.com/photo-1627475320102-d73fcb4eb427?auto=format&fit=crop&w=120&q=80" alt="Ramesh Kumar"/><div><strong>Ramesh Kumar</strong><span>Farmer · Tamil Nadu</span></div><Icon name="chevron" size={16}/></div></div></header><div className="content">
  <section className="intro"><div><p className="eyebrow">SATURDAY, 12 SEPTEMBER</p><h1>Good morning, Ramesh <span>👋</span></h1><p className="intro-copy">Your verified farm activity is building a stronger financial identity.</p></div><button className="outline-button"><Icon name="file" size={17}/> View consent log</button></section>
  <section className="hero-card"><div className="hero-copy"><span className="live-pill"><i></i> CREDIT PROFILE READY</span><h2>Your farm story has value.</h2><p>Turn your verified crops, sales and community trust into better credit opportunities—on your terms.</p><button className="primary-button">View my credit profile <Icon name="arrow" size={18}/></button></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1686683189848-31dc37ae4ed4?auto=format&fit=crop&w=1200&q=85" alt="Paddy fields in Tamil Nadu"/><div className="hero-caption"><Icon name="map" size={16}/><span>Thiruvallur, Tamil Nadu<br/><b>Paddy growing season</b></span></div></div></section>
  <section className="journey"><div className="section-heading"><div><p className="eyebrow">YOUR CREDIT JOURNEY</p><h3>Built from trusted farm data</h3></div><button className="text-button">How it works <Icon name="arrow" size={16}/></button></div><div className="journey-steps">{steps.map(([icon, title, state], i) => <div className="journey-step" key={title}><div className="step-icon"><Icon name={icon}/>{i < 3 && <span className="connector"/>}</div><div><strong>{title}</strong><span><Icon name="check" size={13}/>{state}</span></div></div>)}</div></section>
  <section className="metrics"><article className="metric-card score"><div className="card-row"><span className="card-kicker">CREDIT SCORE</span><button><Icon name="dots"/></button></div><div className="score-body"><div className="score-ring"><span>780</span><small>/ 900</small></div><div><h3>Strong profile</h3><p>Top 18% of farmers in your FPO</p><span className="positive">↑ 42 pts <em>since last season</em></span></div></div><div className="score-foot"><span>Confidence</span><b>High <i></i></b></div></article><article className="metric-card limit"><div className="card-row"><span className="card-kicker">SAFE CREDIT LIMIT</span><Icon name="wallet" size={20}/></div><h2>₹ 2,00,000</h2><p>Recommended based on your expected crop income and verified repayment capacity.</p><div className="limit-bar"><span></span></div><div className="limit-meta"><span>₹0 utilised</span><b>Ready to explore</b></div></article><article className="metric-card farm"><div className="card-row"><span className="card-kicker">FARM SNAPSHOT</span><Icon name="leaf" size={20}/></div><div className="farm-list"><div><span>Land holding</span><b>3.5 acres</b></div><div><span>Current crops</span><b>Paddy, Groundnut</b></div><div><span>Harvest outlook</span><b className="positive">Favourable</b></div></div><button className="text-button">View farm records <Icon name="arrow" size={16}/></button></article></section>
  <section className="lower-grid"><article className="panel records"><div className="section-heading"><div><p className="eyebrow">DATA HEALTH</p><h3>My farm records</h3></div><button className="text-button">See all <Icon name="arrow" size={16}/></button></div>{[["file", "Land & crop records", "Verified", "Today"], ["chart", "Market sales", "Updated", "5 days ago"], ["shield", "Insurance & schemes", "Verified", "2 days ago"]].map(([icon, title, status, date]) => <div className="record-row" key={title}><span className="record-icon"><Icon name={icon}/></span><div><strong>{title}</strong><small>Last updated {date}</small></div><span className={`status ${status === "Verified" ? "verified" : "updated"}`}>{status === "Verified" && <Icon name="check" size={13}/>} {status}</span><Icon name="chevron" size={16}/></div>)}</article><article className="panel activity"><div className="section-heading"><div><p className="eyebrow">RECENT ACTIVITY</p><h3>Updates for you</h3></div><button className="text-button">View all</button></div>{[["Land record verified", "Your 3.5-acre record has been checked", "2 days ago", "green"], ["Paddy sale recorded", "₹48,000 added to your farm income", "5 days ago", "gold"], ["Loan offer unlocked", "Based on your updated credit profile", "1 week ago", "blue"]].map(([title, desc, date, c]) => <div className="activity-row" key={title}><span className={`activity-dot ${c}`}></span><div><strong>{title}</strong><small>{desc}</small></div><time>{date}</time></div>)}</article></section>
  <section className="ownership"><div className="ownership-icon"><Icon name="shield" size={22}/></div><div><strong>Your data. Your decision.</strong><span>Your farm profile is shared with lenders only when you approve a request.</span></div><button className="text-button">Manage consent <Icon name="arrow" size={16}/></button></section>
  </div></main></div>;
}
